# Generated by Django 4.1.7 on 2023-03-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=12)),
                ('community', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('rec_letter', models.BinaryField()),
                ('email', models.CharField(max_length=50)),
                ('final_list', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('SSN', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('administrator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.IntegerField()),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.nominee')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.user')),
            ],
        ),
        migrations.AddField(
            model_name='nominee',
            name='nominee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.user'),
        ),
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contention_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.nominee')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.user')),
            ],
        ),
    ]
