# Generated by Django 4.1.7 on 2023-05-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.BooleanField(default=False)),
                ('vote', models.BooleanField(default=False)),
                ('contention', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Control Content',
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomin_sd', models.DateTimeField(max_length=30, null=True)),
                ('nomin_ed', models.DateTimeField(max_length=30, null=True)),
                ('vote_sd', models.DateTimeField(max_length=30, null=True)),
                ('vote_ed', models.DateTimeField(max_length=30, null=True)),
                ('con_sd', models.DateTimeField(max_length=30, null=True)),
                ('con_ed', models.DateTimeField(max_length=30, null=True)),
                ('nominations_period_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nominee_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('community', models.CharField(choices=[('1', 'اللجنة العلمية'), ('2', 'اللجنة الرياضية'), ('3', 'اللجنة الاجتماعية'), ('4', 'أسرة الجوالة و الخدمات'), ('5', 'اللجنة الثقافية'), ('6', 'اللجنة الفنية'), ('7', 'لجنة الاسر و الرحلات')], max_length=20)),
                ('rec_letter', models.FileField(upload_to='')),
                ('final_list', models.BooleanField(default=False)),
                ('Numofvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Student_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('collegeYear', models.IntegerField(null=True)),
                ('Userkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominations_period_id', models.IntegerField(default=0)),
                ('community', models.CharField(choices=[('1', 'اللجنة العلمية'), ('2', 'اللجنة الرياضية'), ('3', 'اللجنة الاجتماعية'), ('4', 'أسرة الجوالة و الخدمات'), ('5', 'اللجنة الثقافية'), ('6', 'اللجنة الفنية'), ('7', 'لجنة الاسر و الرحلات')], max_length=20)),
                ('nominee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.nominee_user')),
                ('voter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.user_model')),
            ],
        ),
        migrations.AddField(
            model_name='nominee_user',
            name='UserModelKey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.user_model'),
        ),
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.nominee_user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Userkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
