# Generated by Django 4.1.7 on 2023-03-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=12)),
                ('community', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('rec_letter', models.BinaryField()),
                ('email', models.CharField(max_length=50)),
                ('final_list', models.BooleanField()),
                ('nominee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
