# Generated by Django 4.1.7 on 2023-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee_user',
            name='community',
            field=models.CharField(choices=[('1', 'اللجنة العلمية'), ('2', 'اللجنة الرياضية'), ('3', 'اللجنة الاجتماعية'), ('4', 'أسرة الجوالة و الخدمات'), ('5', 'اللجنة الثقافية'), ('6', 'اللجنة الفنية'), ('7', 'لجنة الاسر و الرحلات')], default='1', max_length=30),
        ),
    ]
