# Generated by Django 4.1.7 on 2023-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='Voting_status',
            field=models.BooleanField(default=False),
        ),
    ]
