# Generated by Django 4.1.7 on 2023-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='communityMemberElections_ed',
            field=models.DateTimeField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='communityMemberElections_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
    ]
