# Generated by Django 4.1.7 on 2023-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='electoral_prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnal_pic', models.ImageField(blank=True, upload_to='')),
                ('acheivement_brief', models.TextField()),
                ('program_brief', models.TextField()),
                ('electoral_symbol', models.ImageField(upload_to='')),
                ('electoral_symbol_name', models.CharField(max_length=50)),
            ],
        ),
    ]
