# Generated by Django 4.1.7 on 2023-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee_user',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='nominee_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nominee_user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='nominee_user',
            name='collegeYear',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='collegeYear',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
