# Generated by Django 4.1.7 on 2023-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_nominee_user_name_remove_nominee_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee_user',
            name='phone_no',
            field=models.IntegerField(max_length=12),
        ),
    ]
