# Generated by Django 4.1.7 on 2023-03-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_nominee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='position',
        ),
        migrations.AddField(
            model_name='nominee',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nominee',
            name='Numofvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nominee',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='collegeYear',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='rec_letter',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Nominee_user',
        ),
    ]
