# Generated by Django 4.1.7 on 2023-05-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_user_model_voting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='nominee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_foreign_key_2', to='training.user_model'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_foreign_key_1', to='training.user_model'),
        ),
    ]
