# Generated by Django 4.2.1 on 2023-05-12 22:35

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_nominee_user_rec_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee_user',
            name='rec_letter',
            field=models.FileField(upload_to=training.models.Nominee_user.get_upload_path),
        ),
    ]
