# Generated by Django 4.1.7 on 2023-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_nominee_user_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee_user',
            name='role',
            field=models.CharField(choices=[('1', 'مترشح'), ('2', 'أمين لجنة'), ('3', 'أمين مساعد لجنة'), ('4', 'أمين اتحاد'), ('5', 'أمين مساعد اتحاد'), ('6', 'رئيس اتحاد'), ('7', 'نائب رئيس اتحاد')], default='', max_length=25),
        ),
    ]
