# Generated by Django 4.1.7 on 2023-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_electoral_prog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoral_prog',
            name='electoral_symbol',
            field=models.ImageField(blank=True, upload_to='electoral_symbol'),
        ),
        migrations.AlterField(
            model_name='electoral_prog',
            name='personnal_pic',
            field=models.ImageField(blank=True, upload_to='nominees_pictures'),
        ),
    ]
