# Generated by Django 4.1.7 on 2023-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_vote_nominee_id_alter_vote_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.BooleanField(default=False)),
                ('vote', models.BooleanField(default=False)),
                ('contention', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Control Content',
            },
        ),
    ]
