# Generated by Django 4.1.7 on 2023-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_dates_communitymemberelections_ed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='Voting_1_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_1_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_2_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_2_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_3_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_3_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_4_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_4_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_5_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='Voting_5_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='collegeCommunityTrusteeOreHelperElections_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='collegeCommunityTrusteeOreHelperElections_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='collegeStudentUnionPresidentOrViceElections_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='collegeStudentUnionPresidentOrViceElections_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='con_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='con_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_1_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_1_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_2_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_2_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_3_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_3_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_4_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_4_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_5_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='result_5_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='universityCommunityTrusteeOrHelperElections_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='universityCommunityTrusteeOrHelperElections_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='universityStudentUnionPresidentOrViceElections_ed',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='universityStudentUnionPresidentOrViceElections_sd',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='nominee_user',
            name='community',
            field=models.CharField(choices=[('1', 'اللجنة العلمية'), ('2', 'اللجنة الرياضية'), ('3', 'اللجنة الاجتماعية'), ('4', 'أسرة الجوالة و الخدمات'), ('5', 'اللجنة الثقافية'), ('6', 'اللجنة الفنية'), ('7', 'لجنة الاسر و الرحلات')], default='1', max_length=32),
        ),
    ]
