# Generated by Django 4.1.7 on 2023-05-09 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_current_nom_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='electoral_prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnal_pic', models.ImageField(blank=True, upload_to='nominees_pictures')),
                ('acheivement_brief', models.TextField()),
                ('program_brief', models.TextField()),
                ('electoral_symbol', models.ImageField(blank=True, upload_to='electoral_symbol')),
                ('electoral_symbol_name', models.CharField(max_length=50)),
                ('nominee_key', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.nominee_user')),
            ],
        ),
    ]
