# Generated by Django 4.1.7 on 2023-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomin_sd', models.CharField(max_length=30)),
                ('nomin_ed', models.CharField(max_length=30)),
                ('vote_sd', models.CharField(max_length=30)),
                ('vote_ed', models.CharField(max_length=30)),
                ('con_sd', models.CharField(max_length=30)),
                ('con_ed', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
