# Generated by Django 4.1.7 on 2023-04-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='con_ed',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dates',
            name='con_sd',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dates',
            name='nomin_ed',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dates',
            name='nomin_sd',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dates',
            name='vote_ed',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dates',
            name='vote_sd',
            field=models.DateTimeField(max_length=30),
        ),
    ]
