# Generated by Django 4.1.7 on 2023-03-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_nominee_position_nominee_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voting',
            new_name='Vote',
        ),
    ]
