# Generated by Django 4.1.7 on 2023-04-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_contention_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contention',
            name='contention_id',
        ),
    ]
