# Generated by Django 4.1.7 on 2023-05-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_electoral_prog_electoral_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoral_prog',
            name='nominee_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.nominee_user'),
        ),
    ]
