# Generated by Django 4.1.7 on 2023-03-25 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_rename_voting_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('community', models.CharField(max_length=20)),
                ('collegeYear', models.IntegerField(max_length=20, null=True)),
                ('rec_letter', models.FileField(upload_to='')),
                ('final_list', models.BooleanField(default=False)),
                ('Numofvotes', models.IntegerField(default=0)),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='nominee_id',
        ),
        migrations.AlterField(
            model_name='contention',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='contention',
            name='nominee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.nominee_user'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nominee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.nominee_user'),
        ),
        migrations.DeleteModel(
            name='Nominee',
        ),
    ]
